export const RESULTS_SPINNER = 'RESULTS_SPINNER'; 
export const RECIPE_SPINNER = 'RECIPE_SPINNER'; 
export const FETCH_RECIPES = 'FETCH_RECIPES'; 
export const FETCH_RECIPE = 'FETCH_RECIPE'; 
export const CHANGE_SERVING = "CHANGE_SERVING" 